### ISSUE TITLE
关于数据库的学习

### ISSUE THREAD

**Issue by liubin-vip** [onlyliuxin/coding2017#250]
有很多种数据库，到底该学哪一个？有什么好的学习方法吗？另外如果以后想做DBA该怎么学习充实自己？

**Comment by mzanthem** [comment]
MySql

**Comment by tianmengwei110** [comment]
@mzanthem 为什么不oracle呢

**Comment by AminLiu** [comment]
Mysql吧

**Comment by acusp** [comment]
mysql是开源的，环境安装简单方便学习；
先学习一种关系型的数据库，其他的也就差不多了；主要是学SQL语句，基本都是通用的；
之后在学习非关系型的数据库就行（这个目前一直没空学，嘻嘻～）；

**Comment by tianmengwei110** [comment]
像sql语句语法现在不仅仅只是运维DBA的技能了，开发的也都是必备的了，我觉得要更往深了解还是要了解他的原理，搜索引擎，性能优化，最近在看罗敏的品味性能优化（oracle），大家可以看看，

**Comment by zhang4045** [comment]
mysql，redis

**Comment by felixzhooou** [comment]
可以先从MySQL入门，再去学习Oracle。因为MySQL，开源，容易安装配置，可以专注于学习SQL相关的知识。
没有做过DBA相关的工作，但是数据库是程序员的`硬知识`，需要好好掌握。在这里推荐几本书，希望对你能有帮助。
[学好数据库，这9本书就够了](http://mp.weixin.qq.com/s?__biz=MzI1ODEyOTUwNg==&mid=2653926573&idx=1&sn=f3516a718ed4432bf83bc9f0b01072be#rd)

**Comment by programercat** [comment]
专搞数据库会不会有点枯燥
