### ISSUE TITLE
经常执行delete和update的表是否应该加主键和索引?

### ISSUE THREAD

**Issue by programercat** [onlyliuxin/coding2017#259]
用的是DB2数据库,有一个表用来同步其它系统的数据,数据量可能有几十万,现在的做法是每天删除数据后再导入新数据,这种数据表如何提升查询效率呢?

**Comment by lqhtmc** [comment]
要提交查询效率，肯定要加索引的，索引数最好小于5个。几十万数据不算多，表设计即使加上索引，导入删除数据也不会花很长时间的。

**Comment by gqipan** [comment]
根据你的数据量来觉得，你可以试一下，当加上索引时Delete和Update的效率，对比无索引时Query的效率，比较得失。 不能单纯来说是否加上索引

**Comment by liubin-vip** [comment]
主键一般都要有的，但是索引主要是为了提升查询效率使用的，如果该字段的删除和修改极其频繁，那么每次的修改操作，索引也会更新，这样会导致数据库做了更多的运算，在这种情况下就要避免在该字段建立索引了。

**Comment by xiaoyijian** [comment]
如果删除所有数据，可以使用truncate来提升执行效率

**Comment by programercat** [comment]
多谢各位的回复，可能是我之前描述的不够清楚，其实我想问的是这种频繁执行删除更新操作的表是否需要增加索引来提升查询效率，会不会有其它副作用？   ps:删除数据后重新导入数据这个过程是夜间执行的批量操作，时间上稍微长点也没关系，只要不超过事务时间就行

**Comment by gqipan** [comment]
如果你的删除和更新操作都在晚上执行，为了日常的查询效率建议加上索引

**Comment by lili1991** [comment]
这个需要看使用的什么数据库，并且结合具体的使用场景。如果每次查询的数据量都很少，那建议还是加上索引；如果每次查询的数据量在整个表数据量中的占比比较大，比如10%以上，那么像oracle这样的数据库，建议不使用索引，直接全表扫描；

**Comment by wubingyang** [comment]
你可能搞错了索引的功能，
索引是为了让你更加快速找到所属内容, where 语句
如果频繁增删的表你建立过多索引，反而性能下降。
（底层红黑树实现，增删节点为了维护树结构，会做一些操作）
