### ISSUE TITLE
丢色子作业 求点评指导，求推荐本地实用UML工具

### ISSUE THREAD

**Issue by IdenStudy** [onlyliuxin/coding2017#460]
![oa k5 1zd kpb 2x2 mw9zi](https://user-images.githubusercontent.com/24446529/27522945-61b2f4c0-5a5c-11e7-9187-a4264874dc6b.png)

**Comment by miniyk2012** [comment]
类图的上面2个箭头方向画错了，应该是由DiceGame指向其他2个类
时序图的调用名错了，箭头上的文字应该是被调用者的函数名，而你画的是调用者的函数名，返回箭头上不应该有函数名

**Comment by ShiningChenCode** [comment]
谢谢！ 没注意到这个，学习了！

**Comment by IdenStudy** [comment]
@miniyk2012 谢谢！ 没注意到这个，学习了！

**Comment by programercat** [comment]
你用啥画的？
