### ISSUE TITLE
Spring中一直向传递上下文，这是为了什么这样设计?

### ISSUE THREAD

**Issue by linlazy** [onlyliuxin/coding2017#468]
从
`  public ClassPathXmlApplicationContext(String[] configLocations, boolean refresh, ApplicationContext parent) throws BeansException {
        super(parent);
        this.setConfigLocations(configLocations);
        if(refresh) {
            this.refresh();
        }
`
一直super(parent);
到`    public AbstractApplicationContext(ApplicationContext parent) {
        this();
        this.setParent(parent);
    }`
又为何不继续向上传递了

**Comment by wubingyang** [comment]
职责分离。。
1.这是因为父上下文的属性是在AbstractApplicationContext 中定义的。源码可以看到
2.至于为何不继续向上传递了。 因为AbstractApplicationContext是最顶层抽象类， 把实例传递给接口没意义
