### ISSUE TITLE
分布式应用中，session共享问题

### ISSUE THREAD

**Issue by BigBangGe** [onlyliuxin/coding2017#480]
> 分布式应用中，session共享使用redis存储session； 每次访问拦截后都去请求redis获取session验证用户信息和其他数据  

*这么做会不会影响效率呢？*

**Comment by mddonly** [comment]
以前用过nigix分布式部署，当时是部署了多台tomcat，对于这种分布式tomcat环境，使用的是 msm(memcached session manager)解决的分布式tomcat环境下session共享的问题。

**Comment by onlyliuxin** [comment]
> 分布式应用中，session共享使用redis存储session； 每次访问拦截后都去请求redis获取session验证用户信息和其他数据
> 这么做会不会影响效率呢？

我觉得应该会，　毕竟这些session是在另外一台机器（或多台机器上存储着的）， 存取的时候肯定有网络开销， 只是相对数据库能承受这个开销罢了

**Comment by readke** [comment]
‘效率’ 是相对谁来说的？ 从内存取session可能用0.1ms，从网络取session可能用了100ms，对于机器来讲 0.1ms 和100ms 差了可能1000倍，对于人来讲0.1ms和100ms感觉不会有太大的差别吧

**Comment by BigBangGe** [comment]
*感谢大家解答我的疑惑，thx*
