### ISSUE TITLE
自学java，现在学到了框架部分，请问是先学习Struts2还是直接学spring MVC呢？

### ISSUE THREAD

**Issue by woshishitou** [onlyliuxin/coding2017#488]
听说现在大部分都在用springmvc了，所有有点疑惑，是否还要学习Struts2？

**Comment by woshishitou** [comment]
因为听说现在大部分都在使用springMVC，所以有点疑惑还要不要学Struts2

**Comment by guodongym** [comment]
不需要学了，大概了解就可以，现在除了一些非常老的项目已经很少有人用了，技术更新换代很快的

**Comment by mzanthem** [comment]
看教程写一个简单的springMVC demo，一个struts2的demo。然后体会下二者的不同

**Comment by yangyangxu2016** [comment]
1. 学习spring(必须)
2. 学习springmvc(必须)
3.学习mybatis(必须)
4.学习hibernate(必须)
5.学习struts2(可选)

**Comment by wubingyang** [comment]
学习serlvet(必须)

**Comment by yoda1990** [comment]
了解一下即可吧，现在比较少用了

**Comment by tianmengwei110** [comment]
我饿了，你说我是先吃我左手的饼呢？还是我右手的馒头呢？我不饿的话，我又该怎么吃呢？

**Comment by woshishitou** [comment]
谢谢大家的帮助
