### ISSUE TITLE
在eclipse中编辑代码，标签内属性名自动提示，属性值则没有提示，该怎么做？

### ISSUE THREAD

**Issue by woshishitou** [onlyliuxin/coding2017#548]
就是说能提示出<id>这种属性 ，但是不能提示像 <property name="这里面的值就不能提示"，请大神帮忙，需要什么插件。
在xml、jsp中都是这样，在属性值内按 alt+/ 出现如下提示：
Content Assist not available at the current location
有时候要在属性值里写上jar包中的类名，没有提示会很麻烦。
已经百度和谷歌过，都没有找到解决方案。
谢谢大家了。

**Comment by woshishitou** [comment]
修正一下，现在知道了jsp页面没有提示是因为当时没有导入相应的标签库，但是xml文件还是存在之前描述的问题。

**Comment by Memory-Cunese** [comment]
我也想知道，看视频的时候人家一按快捷键就弹出来了，自己的就是不出来，不知道为什么

**Comment by gqipan** [comment]
@woshishitou XML 需要导入xsd 才有
