### ISSUE TITLE
如何测试Web并发量

### ISSUE THREAD

**Issue by wayss000** [onlyliuxin/coding2017#577]
自己写的Web程序，在本地部署。
电脑配置是：二代i5+10G+西数蓝盘5400转

现在想在本地测试下，Web的并发量可以达到多少，想问问大家有没有什么测试工具，或者测试经验。

**Comment by tianmengwei110** [comment]
apache-jmeter

**Comment by wayss000** [comment]
用了JMeter，并写了个博客记录了下。[JMeter测试网站性能吞吐量](http://blog.csdn.net/qq1332479771/article/details/78035961)
